[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; External Libraries
lib_deps =
; The RFID reader library
    miguelbalboa/MFRC522 @ ^1.4.11

; The JSON parser for reading your API's response
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306

extra_scripts = pre:load_env.py